# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incidentID', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('num_people_involved', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonInvolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fatality', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=10)),
                ('incidentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Incident')),
            ],
        ),
    ]
